# Generated by Django 3.2.15 on 2022-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20220828_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='placement_year',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
