# Generated by Django 3.2.15 on 2022-09-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placement_placement_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='placement_year',
        ),
    ]
