# Generated by Django 3.2.9 on 2022-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_placement_placement_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='current_placement_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='placement',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='placement'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='image',
            field=models.ImageField(blank=True, upload_to='placement'),
        ),
    ]
