# Generated by Django 3.2.9 on 2022-09-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_auto_20220907_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_placement_year', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='placement',
            name='current_placement_year',
        ),
    ]
