# Generated by Django 3.2.15 on 2022-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='poster',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
