# Generated by Django 3.2.15 on 2022-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20220829_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, upload_to='category'),
            preserve_default=False,
        ),
    ]
