# Generated by Django 3.2.15 on 2022-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20220829_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='poster',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='poster',
            field=models.ImageField(default=True, upload_to='poster'),
            preserve_default=False,
        ),
    ]
