# Generated by Django 3.2.9 on 2022-09-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20220829_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-poster', '-name']},
        ),
    ]
