# Generated by Django 3.2.15 on 2022-09-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_or_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campus_image'),
        ),
        migrations.AlterField(
            model_name='video_or_image',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='campus_video'),
        ),
    ]
