# Generated by Django 3.2.15 on 2022-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_brief',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
