# Generated by Django 3.2.15 on 2022-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('file', models.FileField(default=None, max_length=250, null=True, upload_to='results')),
            ],
        ),
    ]
