# Generated by Django 3.2.15 on 2022-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='static/images/events')),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(max_length=30)),
                ('event_desc', models.TextField()),
            ],
        ),
    ]
