# Generated by Django 3.2.15 on 2022-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_homegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegallery',
            name='home_gall',
            field=models.ImageField(upload_to='static/images/home_gallery'),
        ),
    ]
