# Generated by Django 3.2.15 on 2022-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_homegallery_home_gall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='home_gall',
            field=models.ImageField(upload_to='home_gallery'),
        ),
    ]
