# Generated by Django 3.2.15 on 2022-08-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220827_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.FileField(upload_to='exam')),
                ('prev_qp', models.FileField(upload_to='exam')),
            ],
        ),
    ]
