# Generated by Django 3.2.15 on 2022-08-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220828_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
