# Generated by Django 3.2.15 on 2022-08-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
