# Generated by Django 3.2.15 on 2022-08-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='special day')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
    ]
