# Generated by Django 3.2.15 on 2022-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_specialday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='desc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
