# Generated by Django 3.2.15 on 2022-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_specialday_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='desc',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
