# Generated by Django 3.2.15 on 2022-09-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220902_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qpaper',
        ),
        migrations.DeleteModel(
            name='QpLink',
        ),
    ]
