# Generated by Django 3.2.15 on 2022-09-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_category_qp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_name',
            new_name='batch',
        ),
    ]
