# Generated by Django 3.2.15 on 2022-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_sub_name_category_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='qp',
            name='sub_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qp',
            name='year_of_qp',
            field=models.CharField(max_length=130),
        ),
    ]
