# Generated by Django 3.2.15 on 2022-09-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20220902_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='desc',
            new_name='alert_desc',
        ),
    ]
