# Generated by Django 3.2.15 on 2022-09-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_desc_alert_alert_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='testimonial')),
            ],
        ),
    ]
