# Generated by Django 3.2.9 on 2022-09-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BatchinQp',
        ),
    ]
