# Generated by Django 3.2.9 on 2022-09-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20220907_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-notice']},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
