# Generated by Django 3.2.9 on 2022-09-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_date_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=120)),
                ('exam_date', models.DateField()),
                ('exam_sheet_pdf', models.FileField(upload_to='exam_sheet')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
